// EGU 영단어&품사 - 전체 55유닛 1,102단어
// Auto-extracted from PDF

const VOCAB_DATA = [
  {
    unit: 1,
    words: [
      { english: 'knock', korean: '(문을) 두드리다, 노크하다; 노크 소리' },
      { english: 'door', korean: '문' },
      { english: 'window', korean: '창문' },
      { english: 'clean', korean: '깨끗한; 닦다, 청소하다' },
      { english: 'dirty', korean: '더러운, 지저분한' },
      { english: 'room', korean: '방' },
      { english: 'living room', korean: '거실' },
      { english: 'bedroom', korean: '침실' },
      { english: 'bathroom', korean: '욕실' },
      { english: 'kitchen', korean: '부엌, 주방' },
      { english: 'television', korean: '텔레비전' },
      { english: 'telephone', korean: '전화, 전화기' },
      { english: 'table', korean: '탁자, 식탁' },
      { english: 'newspaper', korean: '신문' },
      { english: 'clock', korean: '시계' },
      { english: 'curtain', korean: '커튼' },
      { english: 'key', korean: '열쇠' },
      { english: 'vase', korean: '꽃병' },
      { english: 'umbrella', korean: '우산' },
      { english: 'roof', korean: '지붕' },
    ]
  },
  {
    unit: 2,
    words: [
      { english: 'mirror', korean: '거울' },
      { english: 'soap', korean: '비누' },
      { english: 'shampoo', korean: '샴푸; 머리 감기' },
      { english: 'brush', korean: '솔질을 하다; 붓' },
      { english: 'toothbrush', korean: '칫솔' },
      { english: 'toothpaste', korean: '치약' },
      { english: 'shower', korean: '샤워(하기); 샤워기' },
      { english: 'towel', korean: '수건' },
      { english: 'break', korean: '깨다, 깨지다; 고장 내다; (짧은) 휴식' },
      { english: 'use', korean: '사용하다, 이용하다; 사용, 이용' },
      { english: 'spoon', korean: '숟가락' },
      { english: 'fork', korean: '포크' },
      { english: 'knife', korean: '칼, 나이프' },
      { english: 'chopstick', korean: '젓가락 (한 짝)' },
      { english: 'plate', korean: '접시, 그릇' },
      { english: 'cup', korean: '컵' },
      { english: 'glass', korean: '유리; 유리잔; 안경' },
      { english: 'jar', korean: '(꿀 등을 담는) 병; 단지, 항아리' },
      { english: 'pan', korean: '(손잡이가 달린 얕은) 냄비, 팬' },
      { english: 'refrigerator', korean: '냉장고' },
    ]
  },
  {
    unit: 3,
    words: [
      { english: 'bed', korean: '침대' },
      { english: 'pillow', korean: '베개' },
      { english: 'blanket', korean: '담요, 이불' },
      { english: 'lamp', korean: '램프, 등' },
      { english: 'closet', korean: '벽장' },
      { english: 'dry', korean: '마르다, 말리다; 마른, 건조한' },
      { english: 'wet', korean: '젖은' },
      { english: 'cover', korean: '덮다, 씌우다' },
      { english: 'fan', korean: '선풍기, 부채' },
      { english: 'air conditioner', korean: '에어컨' },
      { english: 'desk', korean: '책상' },
      { english: 'chair', korean: '의자' },
      { english: 'drawer', korean: '서랍' },
      { english: 'computer', korean: '컴퓨터' },
      { english: 'bookshelf', korean: '책장' },
      { english: 'lock', korean: '잠그다' },
      { english: 'toy', korean: '장난감' },
      { english: 'doll', korean: '인형' },
      { english: 'box', korean: '상자' },
      { english: 'wall', korean: '벽, 담' },
    ]
  },
  {
    unit: 4,
    words: [
      { english: 'clothes', korean: '옷, 의복' },
      { english: 'shirt', korean: '셔츠' },
      { english: 'pants', korean: '바지' },
      { english: 'jeans', korean: '청바지' },
      { english: 'skirt', korean: '치마' },
      { english: 'dress', korean: '드레스, 원피스' },
      { english: 'sweater', korean: '스웨터' },
      { english: 'jacket', korean: '재킷, (짧은) 상의' },
      { english: 'tie', korean: '넥타이' },
      { english: 'wear', korean: '입고[신고/쓰고] 있다' },
      { english: 'new', korean: '새, 새로운' },
      { english: 'old', korean: '늙은, 낡은, 오래된' },
      { english: 'shoes', korean: '신발' },
      { english: 'boots', korean: '장화, 부츠' },
      { english: 'socks', korean: '양말' },
      { english: 'button', korean: '단추' },
      { english: 'pocket', korean: '주머니' },
      { english: 'glove', korean: '장갑' },
      { english: 'scarf', korean: '스카프, 목도리' },
      { english: 'ring', korean: '반지; (종을) 울리다, (종이) 울리다' },
    ]
  },
  {
    unit: 5,
    words: [
      { english: 'family', korean: '가족' },
      { english: 'father', korean: '아버지' },
      { english: 'dad', korean: '아빠' },
      { english: 'mother', korean: '어머니' },
      { english: 'mom', korean: '엄마' },
      { english: 'brother', korean: '형, 오빠, 남동생' },
      { english: 'sister', korean: '언니, 누나, 여동생' },
      { english: 'grandfather', korean: '할아버지' },
      { english: 'grandmother', korean: '할머니' },
      { english: 'parents', korean: '부모' },
      { english: 'grandparents', korean: '조부모 ((외)할아버지, (외)할머니)' },
      { english: 'grandchild', korean: '손자, 손녀' },
      { english: 'husband', korean: '남편' },
      { english: 'wife', korean: '아내' },
      { english: 'son', korean: '아들' },
      { english: 'daughter', korean: '딸' },
      { english: 'uncle', korean: '삼촌, 고모부, 이모부' },
      { english: 'aunt', korean: '숙모, 고모, 이모' },
      { english: 'cousin', korean: '사촌' },
      { english: 'introduce', korean: '소개하다' },
      { english: 'live', korean: '살다' },
      { english: 'together', korean: '함께, 같이' },
    ]
  },
  {
    unit: 6,
    words: [
      { english: 'school', korean: '학교' },
      { english: 'teacher', korean: '선생님, 교사' },
      { english: 'teach', korean: '가르치다' },
      { english: 'student', korean: '학생' },
      { english: 'class', korean: '반, 학급; 수업' },
      { english: 'classroom', korean: '교실' },
      { english: 'classmate', korean: '반 친구' },
      { english: 'blackboard', korean: '칠판' },
      { english: 'friend', korean: '친구' },
      { english: 'enter', korean: '들어가다, 입학하다' },
      { english: 'do', korean: '하다' },
      { english: 'homework', korean: '숙제' },
      { english: 'lesson', korean: '수업, 레슨' },
      { english: 'test', korean: '테스트, 시험, 검사' },
      { english: 'grade', korean: '학년; 성적; 등급' },
      { english: 'homeroom', korean: '홈룸 (학급 모두가 모이는 교실)' },
      { english: 'elementary', korean: '초등의' },
      { english: 'learn', korean: '배우다' },
      { english: 'read', korean: '읽다' },
      { english: 'write', korean: '쓰다' },
    ]
  },
  {
    unit: 7,
    words: [
      { english: 'bag', korean: '가방' },
      { english: 'pen', korean: '펜' },
      { english: 'pencil', korean: '연필' },
      { english: 'pencil case', korean: '필통' },
      { english: 'paper', korean: '종이' },
      { english: 'book', korean: '책' },
      { english: 'notebook', korean: '공책' },
      { english: 'textbook', korean: '교과서' },
      { english: 'eraser', korean: '지우개' },
      { english: 'ruler', korean: '자' },
      { english: 'sharp', korean: '날카로운, 뾰족한' },
      { english: 'thick', korean: '두꺼운' },
      { english: 'thin', korean: '얇은, (몸이) 마른' },
      { english: 'borrow', korean: '빌리다' },
      { english: 'scissors', korean: '가위' },
      { english: 'glue', korean: '접착제, 풀' },
      { english: 'crayon', korean: '크레용' },
      { english: 'diary', korean: '일기(장), 수첩' },
      { english: 'dictionary', korean: '사전' },
      { english: 'calendar', korean: '달력' },
    ]
  },
  {
    unit: 8,
    words: [
      { english: 'study', korean: '공부하다; 공부' },
      { english: 'subject', korean: '과목' },
      { english: 'math', korean: '수학' },
      { english: 'science', korean: '과학' },
      { english: 'art', korean: '미술, 예술' },
      { english: 'music', korean: '음악' },
      { english: 'example', korean: '예, 보기' },
      { english: 'exam', korean: '시험' },
      { english: 'quiz', korean: '퀴즈, 간단한 시험' },
      { english: 'fail', korean: '실패하다; (시험에) 떨어지다' },
      { english: 'correct', korean: '맞는, 정확한; 고치다, 바로잡다' },
      { english: 'word', korean: '단어, 낱말' },
      { english: 'sentence', korean: '문장' },
      { english: 'story', korean: '이야기' },
      { english: 'ask', korean: '묻다, 질문하다; 부탁하다' },
      { english: 'question', korean: '질문, 문제' },
      { english: 'answer', korean: '대답하다; 대답' },
      { english: 'repeat', korean: '반복하다, 되풀이하다' },
      { english: 'practice', korean: '연습하다; 연습' },
      { english: 'understand', korean: '이해하다' },
    ]
  },
  {
    unit: 9,
    words: [
      { english: 'sport(s)', korean: '스포츠, 운동' },
      { english: 'soccer', korean: '축구' },
      { english: 'football', korean: '축구, 미식축구' },
      { english: 'baseball', korean: '야구' },
      { english: 'basketball', korean: '농구' },
      { english: 'volleyball', korean: '배구' },
      { english: 'tennis', korean: '테니스' },
      { english: 'table tennis', korean: '탁구' },
      { english: 'badminton', korean: '배드민턴' },
      { english: 'skate', korean: '스케이트를 타다; 스케이트화' },
      { english: 'bat', korean: '방망이, 배트' },
      { english: 'change', korean: '변화시키다, 바꾸다; 변화, 교체' },
      { english: 'game', korean: '게임, 경기' },
      { english: 'player', korean: '선수' },
      { english: 'team', korean: '팀, 조' },
      { english: 'ready', korean: '준비된' },
      { english: 'gym', korean: '체육관' },
      { english: 'stadium', korean: '경기장' },
      { english: 'join', korean: '가입하다; 함께하다' },
      { english: 'sweat', korean: '땀을 흘리다; 땀' },
    ]
  },
  {
    unit: 10,
    words: [
      { english: 'race', korean: '경주, 달리기 (시합)' },
      { english: 'match', korean: '경기, 시합' },
      { english: 'fair', korean: '공정한' },
      { english: 'point', korean: '점수; 요점' },
      { english: 'score', korean: '득점, 스코어; 득점하다' },
      { english: 'win', korean: '이기다; (메달 등을) 따다' },
      { english: 'lose', korean: '지다; 잃어버리다' },
      { english: 'watch', korean: '보다, 지켜보다' },
      { english: 'victory', korean: '승리' },
      { english: 'rule', korean: '규칙' },
      { english: 'goal', korean: '골, 득점; 목표' },
      { english: 'medal', korean: '메달' },
      { english: 'prize', korean: '상' },
      { english: 'champion', korean: '우승자, 챔피언' },
      { english: 'marathon', korean: '마라톤' },
      { english: 'speed', korean: '속도, 속력' },
      { english: 'train', korean: '훈련시키다, 훈련하다' },
      { english: 'cheer', korean: '응원하다; 응원, 환호' },
      { english: 'captain', korean: '주장' },
      { english: 'coach', korean: '감독, 지도자, 코치' },
    ]
  },
  {
    unit: 11,
    words: [
      { english: 'face', korean: '얼굴; (얼굴) 표정' },
      { english: 'eye', korean: '눈' },
      { english: 'nose', korean: '코' },
      { english: 'mouth', korean: '입' },
      { english: 'ear', korean: '귀' },
      { english: 'lip', korean: '입술' },
      { english: 'tooth', korean: '이, 치아' },
      { english: 'head', korean: '머리, 고개' },
      { english: 'neck', korean: '목' },
      { english: 'shoulder', korean: '어깨' },
      { english: 'arm', korean: '팔' },
      { english: 'hand', korean: '손' },
      { english: 'finger', korean: '손가락' },
      { english: 'leg', korean: '다리' },
      { english: 'foot', korean: '발' },
      { english: 'toe', korean: '발가락, 발끝' },
      { english: 'big', korean: '큰' },
      { english: 'small', korean: '작은' },
      { english: 'long', korean: '긴; 오랜' },
      { english: 'short', korean: '짧은; 키가 작은' },
    ]
  },
  {
    unit: 12,
    words: [
      { english: 'tall', korean: '키가 큰, 높은' },
      { english: 'pretty', korean: '예쁜' },
      { english: 'lovely', korean: '사랑스러운' },
      { english: 'beautiful', korean: '아름다운' },
      { english: 'beauty', korean: '아름다움; 미인' },
      { english: 'handsome', korean: '잘생긴' },
      { english: 'ugly', korean: '못생긴, 보기 흉한' },
      { english: 'fat', korean: '뚱뚱한, 살찐' },
      { english: 'slim', korean: '날씬한' },
      { english: 'young', korean: '젊은, 어린' },
      { english: 'hair', korean: '머리(털); 털' },
      { english: 'curly', korean: '곱슬곱슬한' },
      { english: 'strong', korean: '강한, 힘센' },
      { english: 'weak', korean: '약한, 힘이 없는' },
      { english: 'red', korean: '빨간(색의), 붉은; 빨간색, 빨강' },
      { english: 'blue', korean: '파란; 파란색, 파랑' },
      { english: 'green', korean: '녹색의, 초록색의; 초록색' },
      { english: 'white', korean: '흰색의, 하얀; 흰색' },
      { english: 'gray/grey', korean: '회색의; 회색' },
      { english: 'silver', korean: '은(백)색의; 은, 은색' },
    ]
  },
  {
    unit: 13,
    words: [
      { english: 'body', korean: '몸' },
      { english: 'have', korean: '가지다, 있다; 먹다' },
      { english: 'sick', korean: '아픈, 병든' },
      { english: 'cold', korean: '감기; 추운, 차가운' },
      { english: 'fever', korean: '열' },
      { english: 'cough', korean: '기침하다; 기침' },
      { english: 'life', korean: '인생; 생명' },
      { english: 'die', korean: '죽다' },
      { english: 'dead', korean: '죽은' },
      { english: 'care', korean: '관심을 가지다, 상관하다; 돌봄, 보살핌; 조심' },
      { english: 'mind', korean: '마음' },
      { english: 'hurt', korean: '다치게 하다, 아프다; 다친' },
      { english: 'headache', korean: '두통 (머리가 아픔)' },
      { english: 'toothache', korean: '치통 (이가 아픔)' },
      { english: 'stomach', korean: '위, 배' },
      { english: 'stomachache', korean: '복통 (배가 아픔)' },
      { english: 'medicine', korean: '약' },
      { english: 'rest', korean: '휴식; 쉬다' },
      { english: 'health', korean: '건강' },
      { english: 'healthy', korean: '건강한; 건강에 좋은' },
    ]
  },
  {
    unit: 14,
    words: [
      { english: 'happy', korean: '행복한' },
      { english: 'glad', korean: '기쁜, 반가운' },
      { english: 'excited', korean: '신이 난, 흥분한' },
      { english: 'sad', korean: '슬픈' },
      { english: 'angry', korean: '화난' },
      { english: 'upset', korean: '기분이 상한, 화난' },
      { english: 'sorry', korean: '미안한; 유감스러운' },
      { english: 'thank', korean: '감사하다, 고마워하다' },
      { english: 'love', korean: '사랑하다, 무척 좋아하다; 사랑' },
      { english: 'hate', korean: '미워하다, 몹시 싫어하다' },
      { english: 'afraid', korean: '무서워하는, 겁내는' },
      { english: 'worry', korean: '걱정하다' },
      { english: 'worried', korean: '걱정하는' },
      { english: 'fine', korean: '괜찮은; 멋진' },
      { english: 'cry', korean: '울다' },
      { english: 'crazy', korean: '(말이나 행동이) 정상이 아닌, 말도 안 되는' },
      { english: 'serious', korean: '심각한, 진지한' },
      { english: 'look', korean: '보다; ~해 보이다' },
      { english: 'feel', korean: '느끼다; ~한 기분이 들다' },
      { english: 'get', korean: '받다; 얻다; ~되다' },
    ]
  },
  {
    unit: 15,
    words: [
      { english: 'baby', korean: '아기' },
      { english: 'child', korean: '아이, 어린이' },
      { english: 'kid', korean: '아이' },
      { english: 'boy', korean: '소년, 남자아이' },
      { english: 'girl', korean: '소녀, 여자아이' },
      { english: 'man', korean: '(성인) 남자; 사람' },
      { english: 'woman', korean: '(성인) 여자' },
      { english: 'gentleman', korean: '신사' },
      { english: 'lady', korean: '숙녀; 여성' },
      { english: 'person', korean: '사람' },
      { english: 'people', korean: '사람들' },
      { english: 'kind', korean: '친절한' },
      { english: 'friendly', korean: '상냥한, 친절한' },
      { english: 'brave', korean: '용감한' },
      { english: 'careful', korean: '조심스러운, 신중한' },
      { english: 'honest', korean: '정직한' },
      { english: 'polite', korean: '예의 바른, 공손한' },
      { english: 'fun', korean: '재미, 즐거움; 재미있는, 즐거운' },
      { english: 'funny', korean: '우스운, 웃기는' },
      { english: 'smart', korean: '똑똑한, 영리한' },
    ]
  },
  {
    unit: 16,
    words: [
      { english: 'good', korean: '좋은; 잘하는' },
      { english: 'morning', korean: '아침, 오전' },
      { english: 'afternoon', korean: '오후' },
      { english: 'evening', korean: '저녁' },
      { english: 'night', korean: '밤' },
      { english: 'noon', korean: '정오, 낮 12시' },
      { english: 'today', korean: '오늘(은)' },
      { english: 'tonight', korean: '오늘 밤에' },
      { english: 'early', korean: '일찍; 이른' },
      { english: 'late', korean: '늦게; 늦은; 지각한' },
      { english: 'tomorrow', korean: '내일' },
      { english: 'yesterday', korean: '어제' },
      { english: 'date', korean: '날짜' },
      { english: 'time', korean: '시간, 때' },
      { english: 'hour', korean: '한 시간, 시간' },
      { english: 'minute', korean: '(시간 단위의) 분' },
      { english: 'second', korean: '(시간 단위의) 초' },
      { english: 'past', korean: '과거' },
      { english: 'present', korean: '현재; 선물; 현재의' },
      { english: 'future', korean: '미래' },
    ]
  },
  {
    unit: 17,
    words: [
      { english: 'Monday', korean: '월요일' },
      { english: 'Tuesday', korean: '화요일' },
      { english: 'Wednesday', korean: '수요일' },
      { english: 'Thursday', korean: '목요일' },
      { english: 'Friday', korean: '금요일' },
      { english: 'Saturday', korean: '토요일' },
      { english: 'Sunday', korean: '일요일' },
      { english: 'next', korean: '다음의, 옆의' },
      { english: 'last', korean: '지난, 바로 앞의; 마지막의' },
      { english: 'busy', korean: '바쁜' },
      { english: 'day', korean: '하루, 날; 낮' },
      { english: 'week', korean: '주, 일주일' },
      { english: 'weekend', korean: '주말' },
      { english: 'meet', korean: '만나다' },
      { english: 'picnic', korean: '소풍' },
      { english: 'now', korean: '지금, 이제' },
      { english: 'once', korean: '한 번, 1회' },
      { english: 'twice', korean: '두 번, 2회' },
      { english: 'this', korean: '이것; 이 사람; 이' },
      { english: 'that', korean: '저것; 저 사람; 저' },
    ]
  },
  {
    unit: 18,
    words: [
      { english: 'month', korean: '(달력의) 달; 한 달, 개월' },
      { english: 'year', korean: '해, 년; 1년' },
      { english: 'January', korean: '1월' },
      { english: 'February', korean: '2월' },
      { english: 'March', korean: '3월' },
      { english: 'April', korean: '4월' },
      { english: 'May', korean: '5월' },
      { english: 'June', korean: '6월' },
      { english: 'July', korean: '7월' },
      { english: 'August', korean: '8월' },
      { english: 'September', korean: '9월' },
      { english: 'October', korean: '10월' },
      { english: 'November', korean: '11월' },
      { english: 'December', korean: '12월' },
      { english: 'every', korean: '모든; 매 ~, ~마다' },
      { english: 'before', korean: '~ 전에' },
      { english: 'after', korean: '~ 후에' },
      { english: 'during', korean: '(특정 기간의) ~ 동안, ~ 내내' },
      { english: 'then', korean: '그때; 그러고 나서' },
      { english: 'later', korean: '나중에; ~ 뒤에' },
    ]
  },
  {
    unit: 19,
    words: [
      { english: 'birthday', korean: '생일' },
      { english: 'party', korean: '파티' },
      { english: 'cake', korean: '케이크' },
      { english: 'candle', korean: '초' },
      { english: 'gift', korean: '선물' },
      { english: 'age', korean: '나이' },
      { english: 'invite', korean: '초대하다' },
      { english: 'surprise', korean: '놀람; 깜짝 놀라기; 놀라게 하다' },
      { english: 'celebrate', korean: '축하하다, 기념하다' },
      { english: 'laugh', korean: '웃다' },
      { english: 'first', korean: '첫 번째의' },
      { english: 'second', korean: '두 번째의' },
      { english: 'third', korean: '세 번째의' },
      { english: 'fourth', korean: '네 번째의' },
      { english: 'fifth', korean: '다섯 번째의' },
      { english: 'sixth', korean: '여섯 번째의' },
      { english: 'seventh', korean: '일곱 번째의' },
      { english: 'eighth', korean: '여덟 번째의' },
      { english: 'ninth', korean: '아홉 번째의' },
      { english: 'tenth', korean: '열 번째의' },
    ]
  },
  {
    unit: 20,
    words: [
      { english: 'wake', korean: '(잠에서) 깨다, 일어나다; 깨우다' },
      { english: 'exercise', korean: '운동; 운동하다' },
      { english: 'wash', korean: '씻다' },
      { english: 'sleep', korean: '잠자다; 잠, 수면' },
      { english: 'drive', korean: '운전하다' },
      { english: 'bath', korean: '목욕; 욕조' },
      { english: 'always', korean: '항상, 언제나' },
      { english: 'usually', korean: '대개, 보통' },
      { english: 'often', korean: '자주' },
      { english: 'sometimes', korean: '가끔, 때때로' },
      { english: 'never', korean: '결코[절대] ~ 않다' },
      { english: 'wait', korean: '기다리다' },
      { english: 'moment', korean: '잠시, 잠깐; 순간' },
      { english: 'run', korean: '달리다, 뛰다' },
      { english: 'help', korean: '돕다; 도와주다; 도움' },
      { english: 'bad', korean: '나쁜' },
      { english: 'habit', korean: '습관' },
      { english: 'stop', korean: '멈추다; 멈추게 하다' },
      { english: 'bite', korean: '(이빨로) 물다' },
      { english: 'nail', korean: '손톱, 발톱; 못' },
    ]
  },
  {
    unit: 21,
    words: [
      { english: 'store', korean: '가게, 상점' },
      { english: 'restaurant', korean: '식당, 음식점, 레스토랑' },
      { english: 'bakery', korean: '빵집, 제과점' },
      { english: 'church', korean: '교회' },
      { english: 'library', korean: '도서관' },
      { english: 'hospital', korean: '병원' },
      { english: 'drugstore', korean: '약국' },
      { english: 'post office', korean: '우체국' },
      { english: 'police station', korean: '경찰서' },
      { english: 'find', korean: '찾다, 발견하다' },
      { english: 'build', korean: '(건물 등을) 짓다, 세우다' },
      { english: 'building', korean: '건물, 빌딩' },
      { english: 'company', korean: '회사, 기업' },
      { english: 'pool', korean: '수영장' },
      { english: 'park', korean: '공원' },
      { english: 'theater', korean: '극장' },
      { english: 'museum', korean: '박물관' },
      { english: 'zoo', korean: '동물원' },
      { english: 'airport', korean: '공항' },
      { english: 'factory', korean: '공장' },
    ]
  },
  {
    unit: 22,
    words: [
      { english: 'on', korean: '~ (위)에' },
      { english: 'in', korean: '~ (안)에[에서]' },
      { english: 'under', korean: '~ 아래에' },
      { english: 'in front of', korean: '~ 앞에' },
      { english: 'behind', korean: '~ 뒤에' },
      { english: 'next to', korean: '~ 옆에; ~ 다음의' },
      { english: 'between', korean: '~ 사이에' },
      { english: 'around', korean: '~ 주위에, ~ 둘레에' },
      { english: 'over', korean: '(닿지 않게) ~ 위에, ~위로' },
      { english: 'top', korean: '맨 위, 꼭대기' },
      { english: 'middle', korean: '(한)가운데, 중간' },
      { english: 'corner', korean: '모서리; 길모퉁이' },
      { english: 'end', korean: '끝, 말; 끝나다' },
      { english: 'ground', korean: '땅, 땅바닥' },
      { english: 'grass', korean: '풀; 잔디' },
      { english: 'field', korean: '들판, 밭' },
      { english: 'area', korean: '지역, 구역' },
      { english: 'hill', korean: '언덕, (낮은) 산' },
      { english: 'here', korean: '여기에, 이쪽으로' },
      { english: 'there', korean: '거기에, 그곳에' },
    ]
  },
  {
    unit: 23,
    words: [
      { english: 'market', korean: '시장' },
      { english: 'supermarket', korean: '슈퍼마켓' },
      { english: 'shop', korean: '가게, 상점; 사다, 쇼핑하다' },
      { english: 'department store', korean: '백화점' },
      { english: 'buy', korean: '사다' },
      { english: 'sell', korean: '팔다, 판매하다' },
      { english: 'pay', korean: '지불하다, (돈을) 내다' },
      { english: 'price', korean: '가격' },
      { english: 'cheap', korean: '(값이) 싼' },
      { english: 'expensive', korean: '비싼' },
      { english: 'free', korean: '무료의; 자유로운; 한가한' },
      { english: 'sale', korean: '판매; 세일, 할인 판매' },
      { english: 'clerk', korean: '점원, 직원' },
      { english: 'open', korean: '열다; 열려 있는' },
      { english: 'close', korean: '닫다; 가까운' },
      { english: 'choose', korean: '선택하다, 고르다' },
      { english: 'pick', korean: '고르다, (과일 등을) 따다, 꺾다' },
      { english: 'thing', korean: '것, 일; 물건' },
      { english: 'town', korean: '마을, 동네' },
      { english: 'line', korean: '선, 줄' },
    ]
  },
  {
    unit: 24,
    words: [
      { english: 'bank', korean: '은행' },
      { english: 'money', korean: '돈' },
      { english: 'bill', korean: '지폐; 계산서' },
      { english: 'dollar', korean: '달러; 1달러' },
      { english: 'coin', korean: '동전' },
      { english: 'gold', korean: '금; 황금색; 황금색의' },
      { english: 'spend', korean: '(돈을) 쓰다; (시간을) 보내다' },
      { english: 'need', korean: '필요하다' },
      { english: 'copy', korean: '복사(본); 복사하다, 베끼다' },
      { english: 'exchange', korean: '교환하다; 환전하다; 교환; 환전' },
      { english: 'rich', korean: '부유한, 돈 많은' },
      { english: 'poor', korean: '가난한' },
      { english: 'save', korean: '저축하다; 절약하다; 구하다' },
      { english: 'waste', korean: '낭비하다' },
      { english: 'count', korean: '(수를) 세다' },
      { english: 'collect', korean: '모으다, 수집하다' },
      { english: 'add', korean: '더하다, 추가하다' },
      { english: 'divide', korean: '나누다' },
      { english: 'wallet', korean: '지갑' },
      { english: 'enough', korean: '충분한; 충분히' },
    ]
  },
  {
    unit: 25,
    words: [
      { english: 'dish', korean: '접시; 요리' },
      { english: 'meat', korean: '고기' },
      { english: 'chicken', korean: '닭; 닭고기' },
      { english: 'beef', korean: '소고기' },
      { english: 'pork', korean: '돼지고기' },
      { english: 'soup', korean: '수프' },
      { english: 'sugar', korean: '설탕' },
      { english: 'salt', korean: '소금' },
      { english: 'salty', korean: '소금이 든, 짠, 짭짤한' },
      { english: 'spicy', korean: '매운, 양념 맛이 강한' },
      { english: 'meal', korean: '식사' },
      { english: 'order', korean: '주문하다; 명령하다; 순서; 주문; 명령' },
      { english: 'pizza', korean: '피자' },
      { english: 'hamburger', korean: '햄버거' },
      { english: 'bake', korean: '굽다' },
      { english: 'cookie', korean: '쿠키' },
      { english: 'pie', korean: '파이' },
      { english: 'chef', korean: '요리사' },
      { english: 'waiter', korean: '종업원, 웨이터' },
      { english: 'oil', korean: '기름, 오일' },
    ]
  },
  {
    unit: 26,
    words: [
      { english: 'hobby', korean: '취미' },
      { english: 'play', korean: '(악기를) 연주하다; 놀다, (게임 등을) 하다' },
      { english: 'piano', korean: '피아노' },
      { english: 'guitar', korean: '기타' },
      { english: 'drum', korean: '드럼' },
      { english: 'violin', korean: '바이올린' },
      { english: 'sing', korean: '노래하다, (노래를) 부르다' },
      { english: 'listen', korean: '듣다' },
      { english: 'like', korean: '좋아하다' },
      { english: 'favorite', korean: '마음에 드는, 가장 좋아하는' },
      { english: 'activity', korean: '활동' },
      { english: 'interested', korean: '관심[흥미] 있어 하는' },
      { english: 'movie', korean: '영화' },
      { english: 'dance', korean: '춤을 추다; 춤, 무용, 댄스' },
      { english: 'camera', korean: '카메라, 사진기' },
      { english: 'kite', korean: '연' },
      { english: 'jump rope', korean: '줄넘기' },
      { english: 'picture', korean: '그림; 사진' },
      { english: 'puzzle', korean: '퍼즐' },
      { english: 'fish', korean: '물고기, 생선; 낚시하다' },
    ]
  },
  {
    unit: 27,
    words: [
      { english: 'begin', korean: '시작하다; 시작되다' },
      { english: 'character', korean: '성격; 등장인물, 캐릭터' },
      { english: 'king', korean: '왕' },
      { english: 'queen', korean: '여왕, 왕비' },
      { english: 'prince', korean: '왕자' },
      { english: 'princess', korean: '공주' },
      { english: 'angel', korean: '천사' },
      { english: 'palace', korean: '궁, 궁전' },
      { english: 'crown', korean: '왕관' },
      { english: 'adventure', korean: '모험' },
      { english: 'giant', korean: '거인; 거대한' },
      { english: 'hero', korean: '영웅' },
      { english: 'god', korean: '신' },
      { english: 'ghost', korean: '유령, 귀신' },
      { english: 'forever', korean: '영원히' },
      { english: 'dream', korean: '꿈; 꿈을 꾸다' },
      { english: 'imagine', korean: '상상하다' },
      { english: 'create', korean: '만들다, 창조하다' },
      { english: 'novel', korean: '소설' },
      { english: 'cartoon', korean: '(풍자) 만화; 만화 영화' },
    ]
  },
  {
    unit: 28,
    words: [
      { english: 'Korea', korean: '한국' },
      { english: 'China', korean: '중국' },
      { english: 'Japan', korean: '일본' },
      { english: 'India', korean: '인도' },
      { english: 'America', korean: '미국; 아메리카 대륙' },
      { english: 'Germany', korean: '독일' },
      { english: 'England', korean: '(좁은 뜻) 잉글랜드; (넓은 뜻) 영국' },
      { english: 'France', korean: '프랑스' },
      { english: 'Italy', korean: '이탈리아' },
      { english: 'world', korean: '세계' },
      { english: 'visit', korean: '(사람·장소를) 방문하다, 찾아가다' },
      { english: 'stay', korean: '머무르다' },
      { english: 'hotel', korean: '호텔' },
      { english: 'travel', korean: '여행하다[가다]; 여행' },
      { english: 'city', korean: '도시' },
      { english: 'country', korean: '나라, 국가' },
      { english: 'capital', korean: '수도; 대문자' },
      { english: 'village', korean: '마을' },
      { english: 'leave', korean: '떠나다, 출발하다' },
      { english: 'arrive', korean: '도착하다' },
    ]
  },
  {
    unit: 29,
    words: [
      { english: 'pilot', korean: '조종사' },
      { english: 'seat', korean: '자리, 좌석' },
      { english: 'pass', korean: '지나가다; 건네주다; (시험에) 합격하다; 출입증' },
      { english: 'passport', korean: '여권' },
      { english: 'ticket', korean: '표, 승차권' },
      { english: 'fly', korean: '날다; 비행하다; 파리' },
      { english: 'board', korean: '탑승하다; 판자' },
      { english: 'wing', korean: '날개' },
      { english: 'engine', korean: '엔진' },
      { english: 'service', korean: '서비스' },
      { english: 'tour', korean: '여행, 관광, 투어' },
      { english: 'tourist', korean: '관광객' },
      { english: 'guide', korean: '안내인, 가이드; 안내 책자; 안내하다' },
      { english: 'journey', korean: '(특히 멀리 가는) 여행' },
      { english: 'trip', korean: '(짧은) 여행' },
      { english: 'schedule', korean: '일정, 스케줄' },
      { english: 'vacation', korean: '방학, 휴가' },
      { english: 'holiday', korean: '휴일; 방학, 휴가' },
      { english: 'fantastic', korean: '환상적인, 멋진' },
      { english: 'perfect', korean: '완벽한' },
    ]
  },
  {
    unit: 30,
    words: [
      { english: 'camp', korean: '캠핑을 하다; 야영지; 캠프' },
      { english: 'tent', korean: '텐트, 천막' },
      { english: 'map', korean: '지도' },
      { english: 'carry', korean: '가지고 있다[다니다]; 나르다' },
      { english: 'bring', korean: '가져오다, 데려오다' },
      { english: 'backpack', korean: '배낭' },
      { english: 'group', korean: '무리, 집단' },
      { english: 'hungry', korean: '배고픈' },
      { english: 'thirsty', korean: '목이 마른' },
      { english: 'food', korean: '음식' },
      { english: 'dig', korean: '파다' },
      { english: 'hole', korean: '구멍' },
      { english: 'pot', korean: '냄비; 화분' },
      { english: 'fire', korean: '불, 화재' },
      { english: 'stick', korean: '(부러진) 나뭇가지; 막대기' },
      { english: 'outdoor', korean: '야외의, 실외의' },
      { english: 'hide', korean: '숨기다; 숨다' },
      { english: 'climb', korean: '오르다, 올라가다' },
      { english: 'mountain', korean: '산' },
      { english: 'hiking', korean: '하이킹, 등산' },
    ]
  },
  {
    unit: 31,
    words: [
      { english: 'film', korean: '(주로 영국) 영화; 필름' },
      { english: 'magic', korean: '마법, 마술; 마법의, 마술의' },
      { english: 'comedy', korean: '코미디, 희극' },
      { english: 'show', korean: '보여 주다; 쇼, (텔레비전 등의) 프로그램' },
      { english: 'musical', korean: '음악의, 음악적인; 뮤지컬' },
      { english: 'act', korean: '행동하다; 연기하다; 행동' },
      { english: 'actor', korean: '배우' },
      { english: 'actress', korean: '여배우' },
      { english: 'stage', korean: '무대; 단계' },
      { english: 'role', korean: '역할' },
      { english: 'wish', korean: '원하다, 바라다; 소망, 소원' },
      { english: 'song', korean: '노래' },
      { english: 'popular', korean: '인기 있는' },
      { english: 'amazing', korean: '놀라운' },
      { english: 'wonderful', korean: '아주 멋진, 훌륭한' },
      { english: 'excellent', korean: '훌륭한, 탁월한' },
      { english: 'humorous', korean: '재미있는, 유머러스한' },
      { english: 'start', korean: '시작하다' },
      { english: 'finish', korean: '끝내다, 마치다' },
      { english: 'wonder', korean: '궁금하다, 궁금해하다' },
    ]
  },
  {
    unit: 32,
    words: [
      { english: 'event', korean: '행사; 사건' },
      { english: 'card', korean: '카드' },
      { english: 'enjoy', korean: '즐기다, 즐거운 시간을 보내다' },
      { english: 'concert', korean: '콘서트, 연주회' },
      { english: 'festival', korean: '축제' },
      { english: 'wedding', korean: '결혼(식)' },
      { english: 'marry', korean: '결혼하다' },
      { english: 'contest', korean: '대회, 시합' },
      { english: 'march', korean: '행진하다; 행진; 행진곡' },
      { english: 'gather', korean: '모이다, 모으다' },
      { english: 'joy', korean: '기쁨' },
      { english: 'exciting', korean: '신나는, 흥미진진한' },
      { english: 'interesting', korean: '흥미로운, 재미있는' },
      { english: 'band', korean: '밴드, 악단' },
      { english: 'welcome', korean: '맞이하다, 환영하다' },
      { english: 'hall', korean: '홀' },
      { english: 'memory', korean: '기억, 추억' },
      { english: 'balloon', korean: '풍선' },
      { english: 'prepare', korean: '준비하다' },
      { english: 'album', korean: '앨범' },
    ]
  },
  {
    unit: 33,
    words: [
      { english: 'ride', korean: '타다; 타기' },
      { english: 'bicycle', korean: '자전거' },
      { english: 'motorcycle', korean: '오토바이' },
      { english: 'take', korean: '(교통수단을) 타다; 가지고[데리고] 가다' },
      { english: 'car', korean: '차, 자동차' },
      { english: 'bus', korean: '버스' },
      { english: 'taxi', korean: '택시' },
      { english: 'truck', korean: '트럭' },
      { english: 'train', korean: '기차, 열차' },
      { english: 'subway', korean: '지하철' },
      { english: 'airplane', korean: '비행기' },
      { english: 'ship', korean: '(큰) 배, 선박' },
      { english: 'boat', korean: '(작은) 배, 보트' },
      { english: 'way', korean: '길; 방법' },
      { english: 'accident', korean: '사고' },
      { english: 'dangerous', korean: '위험한' },
      { english: 'safe', korean: '안전한' },
      { english: 'burn', korean: '(불에) 타다; 태우다' },
      { english: 'news', korean: '뉴스, 소식' },
      { english: 'happen', korean: '일어나다, 발생하다' },
    ]
  },
  {
    unit: 34,
    words: [
      { english: 'go', korean: '가다' },
      { english: 'come', korean: '오다' },
      { english: 'left', korean: '왼쪽, 좌측; 왼쪽의; 왼쪽으로' },
      { english: 'right', korean: '오른쪽; 옳은; 맞는; 오른쪽의; 오른쪽으로' },
      { english: 'move', korean: '움직이다; 옮기다; 이사하다' },
      { english: 'straight', korean: '똑바로' },
      { english: 'east', korean: '동쪽; 동쪽의; 동쪽으로' },
      { english: 'west', korean: '서쪽; 서쪽의; 서쪽으로' },
      { english: 'south', korean: '남쪽; 남쪽의; 남쪽으로' },
      { english: 'north', korean: '북쪽; 북쪽의; 북쪽으로' },
      { english: 'cross', korean: '(가로질러) 건너다' },
      { english: 'street', korean: '거리, 도로' },
      { english: 'road', korean: '(차가 다니는) 도로, 길' },
      { english: 'sign', korean: '표지판, 간판; 서명하다' },
      { english: 'turn', korean: '돌다, 돌리다' },
      { english: 'return', korean: '돌아오다, 돌아가다' },
      { english: 'far', korean: '멀리' },
      { english: 'up', korean: '위로, 위에, 위쪽으로' },
      { english: 'down', korean: '아래로, 아래에, 아래쪽으로' },
      { english: 'away', korean: '떨어져서; 저쪽으로' },
    ]
  },
  {
    unit: 35,
    words: [
      { english: 'mail', korean: '우편, 우편물' },
      { english: 'letter', korean: '편지' },
      { english: 'name', korean: '이름' },
      { english: 'address', korean: '주소' },
      { english: 'stamp', korean: '우표; 도장' },
      { english: 'envelope', korean: '봉투' },
      { english: 'postcard', korean: '엽서' },
      { english: 'send', korean: '보내다' },
      { english: 'receive', korean: '받다' },
      { english: 'reply', korean: '대답하다; 답장을 보내다; 대답; 답장' },
      { english: 'deliver', korean: '배달하다' },
      { english: 'call', korean: '전화하다; 부르다' },
      { english: 'speak', korean: '이야기하다, 말을 주고 받다' },
      { english: 'say', korean: '말하다' },
      { english: 'tell', korean: '(말·글로) 알리다; 말하다' },
      { english: 'chat', korean: '이야기를 나누다, 수다를 떨다' },
      { english: 'note', korean: '메모, 쪽지' },
      { english: 'voice', korean: '목소리, 음성' },
      { english: 'record', korean: '기록; 기록하다; 녹음하다' },
      { english: 'dialog(ue)', korean: '대화' },
    ]
  },
  {
    unit: 36,
    words: [
      { english: 'rice', korean: '쌀; 밥' },
      { english: 'bread', korean: '빵' },
      { english: 'sandwich', korean: '샌드위치' },
      { english: 'cheese', korean: '치즈' },
      { english: 'butter', korean: '버터' },
      { english: 'egg', korean: '달걀, 계란' },
      { english: 'salad', korean: '샐러드' },
      { english: 'noodle', korean: '국수, 면' },
      { english: 'honey', korean: '(벌)꿀' },
      { english: 'dessert', korean: '디저트, 후식' },
      { english: 'eat', korean: '먹다' },
      { english: 'breakfast', korean: '아침 (식사)' },
      { english: 'lunch', korean: '점심 (식사)' },
      { english: 'dinner', korean: '저녁 (식사)' },
      { english: 'drink', korean: '마시다; 음료, 마실 것' },
      { english: 'milk', korean: '우유' },
      { english: 'tea', korean: '차' },
      { english: 'coffee', korean: '커피' },
      { english: 'delicious', korean: '아주 맛있는' },
      { english: 'sweet', korean: '단, 달콤한' },
    ]
  },
  {
    unit: 37,
    words: [
      { english: 'many', korean: '(수가) 많은' },
      { english: 'much', korean: '(양이) 많은' },
      { english: 'some', korean: '약간의, 몇몇의' },
      { english: 'few', korean: '(수가) 거의 없는' },
      { english: 'a few', korean: '(수가) 약간의, 여러, 몇' },
      { english: 'little', korean: '(양이) 거의 없는; 작은; 어린' },
      { english: 'a little', korean: '(양이) 약간의, 조금의' },
      { english: 'hundred', korean: '백, 100; 백의, 100의' },
      { english: 'thousand', korean: '천, 1000; 천의, 1000의' },
      { english: 'million', korean: '백만, 100만; 백만의, 100만의' },
      { english: 'fill', korean: '(가득) 채우다' },
      { english: 'full', korean: '가득 찬, 가득한' },
      { english: 'empty', korean: '빈, 비어 있는' },
      { english: 'fruit', korean: '과일' },
      { english: 'vegetable', korean: '채소' },
      { english: 'basket', korean: '바구니' },
      { english: 'snack', korean: '간식' },
      { english: 'all', korean: '모든, 전부의' },
      { english: 'each', korean: '각각의, 각자의' },
      { english: 'half', korean: '반, 절반; 반의, 절반의' },
    ]
  },
  {
    unit: 38,
    words: [
      { english: 'apple', korean: '사과' },
      { english: 'banana', korean: '바나나' },
      { english: 'orange', korean: '오렌지; 오렌지[주황]색; 오렌지[주황]색의' },
      { english: 'grape', korean: '포도' },
      { english: 'strawberry', korean: '딸기' },
      { english: 'lemon', korean: '레몬' },
      { english: 'pear', korean: '배' },
      { english: 'watermelon', korean: '수박' },
      { english: 'juice', korean: '주스, 즙' },
      { english: 'sour', korean: '(맛이) 신' },
      { english: 'tomato', korean: '토마토' },
      { english: 'carrot', korean: '당근' },
      { english: 'potato', korean: '감자' },
      { english: 'corn', korean: '옥수수' },
      { english: 'onion', korean: '양파' },
      { english: 'cucumber', korean: '오이' },
      { english: 'pumpkin', korean: '호박' },
      { english: 'bean', korean: '콩' },
      { english: 'nut', korean: '견과(류), 나무 열매 (껍질이 단단한 호두·밤 등)' },
      { english: 'fresh', korean: '신선한' },
    ]
  },
  {
    unit: 39,
    words: [
      { english: 'farm', korean: '농장' },
      { english: 'hen', korean: '암탉' },
      { english: 'sheep', korean: '양' },
      { english: 'cow', korean: '암소, 젖소' },
      { english: 'goat', korean: '염소' },
      { english: 'duck', korean: '오리' },
      { english: 'goose', korean: '거위' },
      { english: 'pig', korean: '돼지' },
      { english: 'rabbit', korean: '토끼' },
      { english: 'horse', korean: '말' },
      { english: 'mouse', korean: '쥐; (컴퓨터) 마우스' },
      { english: 'feed', korean: '먹이를 주다, 먹이다' },
      { english: 'catch', korean: '잡다, 받다; (붙)잡다' },
      { english: 'ant', korean: '개미' },
      { english: 'butterfly', korean: '나비' },
      { english: 'bee', korean: '벌' },
      { english: 'bug', korean: '벌레, 작은 곤충' },
      { english: 'worm', korean: '(땅속에 사는) 벌레' },
      { english: 'mosquito', korean: '모기' },
      { english: 'spider', korean: '거미' },
    ]
  },
  {
    unit: 40,
    words: [
      { english: 'wild', korean: '야생의; 자연 그대로의' },
      { english: 'animal', korean: '동물' },
      { english: 'elephant', korean: '코끼리' },
      { english: 'bear', korean: '곰' },
      { english: 'squirrel', korean: '다람쥐' },
      { english: 'wolf', korean: '늑대' },
      { english: 'fox', korean: '여우' },
      { english: 'giraffe', korean: '기린' },
      { english: 'kangaroo', korean: '캥거루' },
      { english: 'deer', korean: '사슴' },
      { english: 'pet', korean: '애완동물' },
      { english: 'dog', korean: '개' },
      { english: 'cat', korean: '고양이' },
      { english: 'bird', korean: '새' },
      { english: 'parrot', korean: '앵무새' },
      { english: 'turtle', korean: '거북, 바다거북' },
      { english: 'tail', korean: '꼬리' },
      { english: 'cute', korean: '귀여운' },
      { english: 'want', korean: '원하다, ~하고 싶어 하다' },
      { english: 'hunt', korean: '사냥하다' },
    ]
  },
  {
    unit: 41,
    words: [
      { english: 'nature', korean: '자연' },
      { english: 'land', korean: '육지, 땅' },
      { english: 'island', korean: '섬' },
      { english: 'sea', korean: '바다' },
      { english: 'river', korean: '강' },
      { english: 'lake', korean: '호수' },
      { english: 'pond', korean: '연못' },
      { english: 'cave', korean: '동굴' },
      { english: 'forest', korean: '(광대한) 숲, 삼림' },
      { english: 'wood', korean: '나무, 목재; 숲' },
      { english: 'jungle', korean: '밀림, 정글' },
      { english: 'desert', korean: '사막' },
      { english: 'valley', korean: '골짜기, 계곡' },
      { english: 'rock', korean: '바위' },
      { english: 'stone', korean: '돌' },
      { english: 'plant', korean: '식물; 심다' },
      { english: 'soil', korean: '흙, 토양' },
      { english: 'mud', korean: '진흙' },
      { english: 'native', korean: '출생지의, 모국의; 원주민의; 토종의' },
      { english: 'discover', korean: '발견하다' },
    ]
  },
  {
    unit: 42,
    words: [
      { english: 'ocean', korean: '대양, 바다' },
      { english: 'beach', korean: '해변, 바닷가' },
      { english: 'wave', korean: '파도, 물결' },
      { english: 'sand', korean: '모래; 모래밭' },
      { english: 'sandcastle', korean: '모래성' },
      { english: 'sail', korean: '항해하다' },
      { english: 'deep', korean: '깊은' },
      { english: 'swim', korean: '수영하다, 헤엄치다' },
      { english: 'lie', korean: '눕다, 누워 있다' },
      { english: 'relax', korean: '휴식을 취하다; 긴장을 풀다' },
      { english: 'put on', korean: '입다, 신다, 쓰다' },
      { english: 'take off', korean: '(옷 등을) 벗다' },
      { english: 'hat', korean: '모자' },
      { english: 'sunglasses', korean: '선글라스' },
      { english: 'sandals', korean: '샌들' },
      { english: 'view', korean: '전망, 경치; 견해, 의견' },
      { english: 'peaceful', korean: '평화로운' },
      { english: 'dolphin', korean: '돌고래' },
      { english: 'whale', korean: '고래' },
      { english: 'shark', korean: '상어' },
    ]
  },
  {
    unit: 43,
    words: [
      { english: 'sky', korean: '하늘' },
      { english: 'sun', korean: '해, 태양' },
      { english: 'moon', korean: '달' },
      { english: 'star', korean: '별' },
      { english: 'cloud', korean: '구름' },
      { english: 'rain', korean: '비' },
      { english: 'rainbow', korean: '무지개' },
      { english: 'wind', korean: '바람' },
      { english: 'bright', korean: '밝은, 빛나는' },
      { english: 'dark', korean: '어두운, 캄캄한' },
      { english: 'flower', korean: '꽃' },
      { english: 'tree', korean: '나무' },
      { english: 'leaf', korean: '잎' },
      { english: 'seed', korean: '씨, 씨앗' },
      { english: 'sunflower', korean: '해바라기' },
      { english: 'rose', korean: '장미' },
      { english: 'tulip', korean: '튤립' },
      { english: 'lily', korean: '백합' },
      { english: 'grow', korean: '자라다; (식물을) 기르다, 재배하다' },
      { english: 'fall', korean: '떨어지다, 내리다; 넘어지다' },
    ]
  },
  {
    unit: 44,
    words: [
      { english: 'weather', korean: '날씨' },
      { english: 'hot', korean: '더운, 뜨거운' },
      { english: 'freeze', korean: '얼다, 얼리다' },
      { english: 'warm', korean: '따뜻한' },
      { english: 'cool', korean: '시원한' },
      { english: 'sunny', korean: '화창한' },
      { english: 'cloudy', korean: '흐린, 구름 낀' },
      { english: 'foggy', korean: '안개 낀' },
      { english: 'windy', korean: '바람이 부는' },
      { english: 'rainy', korean: '비가 오는' },
      { english: 'snowy', korean: '눈이 내리는, 눈이 많은' },
      { english: 'stormy', korean: '폭풍우가 몰아치는' },
      { english: 'clear', korean: '(날씨가) 맑은; 분명한' },
      { english: 'so', korean: '정말, 너무' },
      { english: 'sunshine', korean: '햇빛, 햇살' },
      { english: 'season', korean: '계절; 철, 시즌' },
      { english: 'spring', korean: '봄' },
      { english: 'summer', korean: '여름' },
      { english: 'autumn/fall', korean: '가을' },
      { english: 'winter', korean: '겨울' },
    ]
  },
  {
    unit: 45,
    words: [
      { english: 'earth', korean: '지구; 땅' },
      { english: 'water', korean: '물' },
      { english: 'air', korean: '공기, 대기' },
      { english: 'gas', korean: '기체, 가스' },
      { english: 'pollution', korean: '오염' },
      { english: 'smoke', korean: '연기; 담배를 피우다' },
      { english: 'protect', korean: '보호하다' },
      { english: 'destroy', korean: '파괴하다' },
      { english: 'environment', korean: '환경' },
      { english: 'harmony', korean: '조화, 화합' },
      { english: 'recycle', korean: '재활용하다' },
      { english: 'plastic', korean: '플라스틱; 플라스틱[비닐]으로 된' },
      { english: 'trash', korean: '쓰레기' },
      { english: 'garbage', korean: '(음식물 등의) 쓰레기' },
      { english: 'throw away', korean: '버리다' },
      { english: 'pick up', korean: '~을 집다[줍다], 들어 올리다; ~를 (차에) 태우러 가다' },
      { english: 'try', korean: '노력하다; 시도하다' },
      { english: 'turn on', korean: '켜다' },
      { english: 'turn off', korean: '끄다' },
      { english: 'switch', korean: '스위치' },
    ]
  },
  {
    unit: 46,
    words: [
      { english: 'see', korean: '보다' },
      { english: 'hear', korean: '듣다' },
      { english: 'smell', korean: '~한 냄새가 나다; 냄새, 향' },
      { english: 'taste', korean: '~ 맛이 나다; 맛' },
      { english: 'sound', korean: '~인 것 같다, ~처럼 들리다; 소리' },
      { english: 'touch', korean: '만지다, 건드리다' },
      { english: 'quick', korean: '빠른, 신속한' },
      { english: 'fast', korean: '빠른; 빨리, 빠르게' },
      { english: 'slow', korean: '느린' },
      { english: 'high', korean: '높은; 높이, 높게' },
      { english: 'low', korean: '낮은; 낮게' },
      { english: 'quiet', korean: '조용한' },
      { english: 'loud', korean: '(소리가) 큰, 시끄러운' },
      { english: 'noise', korean: '(듣기 싫은) 소음, 소리' },
      { english: 'noisy', korean: '시끄러운, 떠들썩한' },
      { english: 'simple', korean: '간단한, 단순한' },
      { english: 'easy', korean: '쉬운' },
      { english: 'difficult', korean: '어려운' },
      { english: 'great', korean: '훌륭한, 위대한; 아주 좋은' },
      { english: 'terrible', korean: '끔찍한; 형편없는' },
    ]
  },
  {
    unit: 47,
    words: [
      { english: 'circle', korean: '원, 동그라미' },
      { english: 'square', korean: '정사각형' },
      { english: 'triangle', korean: '삼각형' },
      { english: 'shape', korean: '모양, 형태' },
      { english: 'round', korean: '둥근, 원형의' },
      { english: 'color', korean: '색, 색깔' },
      { english: 'draw', korean: '(연필 등으로) 그리다' },
      { english: 'paint', korean: '페인트; 페인트를 칠하다; (그림물감으로) 그리다' },
      { english: 'make', korean: '만들다' },
      { english: 'cut', korean: '자르다' },
      { english: 'wide', korean: '넓은' },
      { english: 'narrow', korean: '좁은' },
      { english: 'large', korean: '(규모가) 큰; (양이) 많은' },
      { english: 'huge', korean: '거대한, 막대한' },
      { english: 'light', korean: '빛; (전)등; 밝은; 가벼운' },
      { english: 'heavy', korean: '무거운' },
      { english: 'side', korean: '쪽; 측면, 옆면' },
      { english: 'stair', korean: '계단' },
      { english: 'gate', korean: '문, 대문' },
      { english: 'size', korean: '크기; 사이즈' },
    ]
  },
  {
    unit: 48,
    words: [
      { english: 'sit', korean: '앉다' },
      { english: 'stand', korean: '서 있다; 일어서다' },
      { english: 'walk', korean: '걷다, 걸어가다' },
      { english: 'jump', korean: '뛰다, 점프하다' },
      { english: 'throw', korean: '던지다' },
      { english: 'kick', korean: '(발로) 차다' },
      { english: 'hit', korean: '때리다, 치다' },
      { english: 'push', korean: '밀다' },
      { english: 'hold', korean: '잡고[들고/안고] 있다' },
      { english: 'ball', korean: '공' },
      { english: 'raise', korean: '들어 올리다, 들다; 키우다' },
      { english: 'lift', korean: '들어 올리다' },
      { english: 'shout', korean: '외치다, 소리치다' },
      { english: 'roll', korean: '구르다, 굴러가다' },
      { english: 'hurry', korean: '서두르다' },
      { english: 'shut', korean: '닫다, 닫히다' },
      { english: 'shake', korean: '흔들리다, 흔들다' },
      { english: 'bottle', korean: '병' },
      { english: 'swing', korean: '그네; 흔들리다, 흔들다' },
      { english: 'slide', korean: '미끄럼틀; 미끄러지다' },
    ]
  },
  {
    unit: 49,
    words: [
      { english: 'fix', korean: '고정하다; 수리하다, 바로잡다' },
      { english: 'house', korean: '집, 주택' },
      { english: 'home', korean: '(가족이 함께 사는) 집, 가정; 집에, 집으로' },
      { english: 'floor', korean: '바닥; (건물의) 층' },
      { english: 'elevator', korean: '엘리베이터' },
      { english: 'ceiling', korean: '천장' },
      { english: 'garden', korean: '정원, 뜰' },
      { english: 'bench', korean: '벤치, 긴 의자' },
      { english: 'mix', korean: '섞다, 혼합하다' },
      { english: 'style', korean: '방식; (옷 등의) 스타일' },
      { english: 'design', korean: '디자인; 디자인하다, 설계하다' },
      { english: 'nice', korean: '좋은, 멋진' },
      { english: 'hard', korean: '단단한, 딱딱한; 어려운; 열심히' },
      { english: 'soft', korean: '부드러운, 푹신한' },
      { english: 'useful', korean: '유용한' },
      { english: 'tired', korean: '피곤한, 지친' },
      { english: 'near', korean: '가까운; 가까이; ~에서 가까이' },
      { english: 'bridge', korean: '다리' },
      { english: 'traffic', korean: '차량들, 교통(량)' },
      { english: 'station', korean: '역, 정거장' },
    ]
  },
  {
    unit: 50,
    words: [
      { english: 'job', korean: '일, 직장, 직업' },
      { english: 'become', korean: '~이 되다' },
      { english: 'scientist', korean: '과학자' },
      { english: 'farmer', korean: '농부' },
      { english: 'police officer', korean: '경찰관' },
      { english: 'firefighter', korean: '소방관' },
      { english: 'writer', korean: '작가' },
      { english: 'singer', korean: '가수' },
      { english: 'musician', korean: '음악가, 뮤지션' },
      { english: 'artist', korean: '화가; 예술가' },
      { english: 'cook', korean: '요리사; 요리하다' },
      { english: 'designer', korean: '디자이너' },
      { english: 'model', korean: '(의류) 모델; (상품의) 모델; 모형' },
      { english: 'nurse', korean: '간호사' },
      { english: 'doctor', korean: '의사' },
      { english: 'dentist', korean: '치과의사' },
      { english: 'driver', korean: '운전자, 기사' },
      { english: 'president', korean: '대통령' },
      { english: 'lawyer', korean: '변호사' },
      { english: 'famous', korean: '유명한' },
    ]
  },
  {
    unit: 51,
    words: [
      { english: 'office', korean: '사무실' },
      { english: 'business', korean: '사업; 일, 업무' },
      { english: 'work', korean: '일하다; 일' },
      { english: 'meeting', korean: '회의' },
      { english: 'report', korean: '보고(서); 보고하다' },
      { english: 'review', korean: '복습하다; 다시 검토하다; 검토' },
      { english: 'solve', korean: '풀다, 해결하다' },
      { english: 'information', korean: '정보' },
      { english: 'speech', korean: '연설' },
      { english: 'place', korean: '장소' },
      { english: 'check', korean: '확인하다, 점검하다; 확인, 점검' },
      { english: 'list', korean: '목록, 명단' },
      { english: 'set', korean: '놓다, 두다; 정하다' },
      { english: 'focus', korean: '집중하다, 집중시키다' },
      { english: 'print', korean: '인쇄하다' },
      { english: 'file', korean: '파일, 서류철; (컴퓨터) 파일' },
      { english: 'course', korean: '강좌, 코스' },
      { english: 'again', korean: '다시, 한 번 더' },
      { english: 'soon', korean: '곧, 머지않아' },
      { english: 'until', korean: '~까지' },
    ]
  },
  {
    unit: 52,
    words: [
      { english: 'problem', korean: '문제; (시험 등의) 문제' },
      { english: 'mistake', korean: '실수' },
      { english: 'fault', korean: '잘못' },
      { english: 'matter', korean: '(처리해야 할) 문제, 일' },
      { english: 'reason', korean: '이유' },
      { english: 'lead', korean: '안내하다, 이끌다; (결과적으로) ~에 이르다' },
      { english: 'handle', korean: '손잡이; 다루다, 처리하다' },
      { english: 'only', korean: '오직, 유일한' },
      { english: 'true', korean: '사실인; 진짜의' },
      { english: 'stupid', korean: '어리석은' },
      { english: 'fact', korean: '사실' },
      { english: 'secret', korean: '비밀' },
      { english: 'advice', korean: '충고, 조언' },
      { english: 'excuse', korean: '변명' },
      { english: 'promise', korean: '약속; 약속하다' },
      { english: 'keep', korean: '유지하다; (약속, 비밀 등을) 지키다' },
      { english: 'believe', korean: '믿다' },
      { english: 'mean', korean: '의미하다, 뜻하다' },
      { english: 'strange', korean: '이상한' },
      { english: 'nervous', korean: '긴장한, 초조한' },
    ]
  },
  {
    unit: 53,
    words: [
      { english: 'wrong', korean: '틀린, 잘못된' },
      { english: 'sure', korean: '확신하는, 확실히 아는' },
      { english: 'idea', korean: '생각, 아이디어' },
      { english: 'opinion', korean: '의견' },
      { english: 'think', korean: '생각하다' },
      { english: 'guess', korean: '추측하다, 짐작하다' },
      { english: 'discuss', korean: '논의하다, 토론하다' },
      { english: 'forget', korean: '잊다, 잊어버리다' },
      { english: 'remember', korean: '기억하다' },
      { english: 'plan', korean: '계획; 계획하다' },
      { english: 'hope', korean: '바라다, 희망하다; 희망' },
      { english: 'know', korean: '알다' },
      { english: 'communicate', korean: '의사소통을 하다' },
      { english: 'complain', korean: '불평하다, 항의하다' },
      { english: 'both', korean: '양쪽의, 둘 다의' },
      { english: 'important', korean: '중요한' },
      { english: 'give', korean: '주다' },
      { english: 'agree', korean: '동의하다' },
      { english: 'share', korean: '공유하다' },
      { english: 'talk', korean: '말하다, 이야기하다' },
    ]
  },
  {
    unit: 54,
    words: [
      { english: 'global', korean: '세계적인, 지구의' },
      { english: 'foreign', korean: '외국의' },
      { english: 'culture', korean: '문화' },
      { english: 'history', korean: '역사' },
      { english: 'traditional', korean: '전통의, 전통적인' },
      { english: 'modern', korean: '현대의, 현대적인' },
      { english: 'smile', korean: '미소 짓다; 미소' },
      { english: 'gesture', korean: '몸짓, 제스처' },
      { english: 'heart', korean: '마음; 심장' },
      { english: 'accept', korean: '받아들이다, 인정하다' },
      { english: 'follow', korean: '따라가다[오다]; 따르다' },
      { english: 'human', korean: '인간의, 인류의; 인간, 사람' },
      { english: 'kill', korean: '죽이다' },
      { english: 'fight', korean: '싸우다; 싸움' },
      { english: 'war', korean: '전쟁' },
      { english: 'peace', korean: '평화' },
      { english: 'flag', korean: '(국)기, 깃발' },
      { english: 'same', korean: '같은' },
      { english: 'different', korean: '다른' },
      { english: 'chance', korean: '기회; 가능성' },
    ]
  },
  {
    unit: 55,
    words: [
      { english: 'robot', korean: '로봇' },
      { english: 'rocket', korean: '로켓' },
      { english: 'control', korean: '지배하다; 통제[제어]하다; 지배; 통제[제어]' },
      { english: 'engineer', korean: '기술자, 엔지니어' },
      { english: 'energy', korean: '에너지' },
      { english: 'power', korean: '힘; 권력; 동력' },
      { english: 'heat', korean: '열, 열기' },
      { english: 'space', korean: '우주; 공간' },
      { english: 'spaceship', korean: '우주선' },
      { english: 'astronaut', korean: '우주 비행사' },
      { english: 'step', korean: '(발)걸음; 단계' },
      { english: 'real', korean: '진짜의, 현실적인' },
      { english: 'trouble', korean: '곤란, 문제' },
      { english: 'put', korean: '놓다, 두다, 넣다' },
      { english: 'let', korean: '~하게 하다, 허락하다' },
      { english: 'other', korean: '(그 밖의) 다른; 다른 사람[것]' },
      { english: 'piece', korean: '한 부분[조각]' },
      { english: 'lucky', korean: '행운의, 운이 좋은' },
      { english: 'well', korean: '잘' },
      { english: 'yet', korean: '아직' },
    ]
  },
];
