/* Word Image Mapping - 단어별 이미지 경로 */
const WORD_IMAGES = {
  // Unit 1
  'knock': 'assets/images/unit1/knock.png',
  'door': 'assets/images/unit1/door.png',
  'window': 'assets/images/unit1/window.png',
  'clean': 'assets/images/unit1/clean.png',
  'dirty': 'assets/images/unit1/dirty.png',
  'room': 'assets/images/unit1/room.png',
  'living room': 'assets/images/unit1/living_room.png',
  'bedroom': 'assets/images/unit1/bedroom.png',
  'bathroom': 'assets/images/unit1/bathroom.png',
  'kitchen': 'assets/images/unit1/kitchen.png',
  'television': 'assets/images/unit1/television.png',
  'telephone': 'assets/images/unit1/telephone.png',
  'table': 'assets/images/unit1/table.png',
  'newspaper': 'assets/images/unit1/newspaper.png',
  'clock': 'assets/images/unit1/clock.png',
  'curtain': 'assets/images/unit1/curtain.png',
  'key': 'assets/images/unit1/key.png',
  'vase': 'assets/images/unit1/vase.png',
  'umbrella': 'assets/images/unit1/umbrella.png',
  'roof': 'assets/images/unit1/roof.png',
  // Unit 2
  'mirror': 'assets/images/unit2/mirror.png',
  'soap': 'assets/images/unit2/soap.png',
  'shampoo': 'assets/images/unit2/shampoo.png',
  'brush': 'assets/images/unit2/brush.png',
  'toothbrush': 'assets/images/unit2/toothbrush.png',
  'toothpaste': 'assets/images/unit2/toothpaste.png',
  'shower': 'assets/images/unit2/shower.png',
  'towel': 'assets/images/unit2/towel.png',
  'break': 'assets/images/unit2/break.png',
  'use': 'assets/images/unit2/use.png',
  'spoon': 'assets/images/unit2/spoon.png',
  'fork': 'assets/images/unit2/fork.png',
  'knife': 'assets/images/unit2/knife.png',
  'chopstick': 'assets/images/unit2/chopstick.png',
  'plate': 'assets/images/unit2/plate.png',
  'cup': 'assets/images/unit2/cup.png',
  'glass': 'assets/images/unit2/glass.png',
  'jar': 'assets/images/unit2/jar.png',
  'pan': 'assets/images/unit2/pan.png',
  'refrigerator': 'assets/images/unit2/refrigerator.png',
  // Unit 3
  'bed': 'assets/images/unit3/bed.png',
  'pillow': 'assets/images/unit3/pillow.png',
  'blanket': 'assets/images/unit3/blanket.png',
  'lamp': 'assets/images/unit3/lamp.png',
  'closet': 'assets/images/unit3/closet.png',
  'dry': 'assets/images/unit3/dry.png',
  'wet': 'assets/images/unit3/wet.png',
  'cover': 'assets/images/unit3/cover.png',
  'fan': 'assets/images/unit3/fan.png',
  'air conditioner': 'assets/images/unit3/air_conditioner.png',
  'desk': 'assets/images/unit3/desk.png',
  'chair': 'assets/images/unit3/chair.png',
  'drawer': 'assets/images/unit3/drawer.png',
  'computer': 'assets/images/unit3/computer.png',
  'bookshelf': 'assets/images/unit3/bookshelf.png',
  'lock': 'assets/images/unit3/lock.png',
  'toy': 'assets/images/unit3/toy.png',
  'doll': 'assets/images/unit3/doll.png',
  'box': 'assets/images/unit3/box.png',
  'wall': 'assets/images/unit3/wall.png',
  // Unit 4
  'clothes': 'assets/images/unit4/clothes.png',
  'shirt': 'assets/images/unit4/shirt.png',
  'pants': 'assets/images/unit4/pants.png',
  'jeans': 'assets/images/unit4/jeans.png',
  'skirt': 'assets/images/unit4/skirt.png',
  'dress': 'assets/images/unit4/dress.png',
  'sweater': 'assets/images/unit4/sweater.png',
  'jacket': 'assets/images/unit4/jacket.png',
  'tie': 'assets/images/unit4/tie.png',
  'wear': 'assets/images/unit4/wear.png',
  'new': 'assets/images/unit4/new.png',
  'old': 'assets/images/unit4/old.png',
  'shoes': 'assets/images/unit4/shoes.png',
  'boots': 'assets/images/unit4/boots.png',
  'socks': 'assets/images/unit4/socks.png',
  'button': 'assets/images/unit4/button.png',
  'pocket': 'assets/images/unit4/pocket.png',
  'gloves': 'assets/images/unit4/gloves.png',
  'scarf': 'assets/images/unit4/scarf.png',
  'ring': 'assets/images/unit4/ring.png',
  // Unit 5
  'family': 'assets/images/unit5/family.png',
  'father': 'assets/images/unit5/father.png',
  'mother': 'assets/images/unit5/mother.png',
  'brother': 'assets/images/unit5/brother.png',
  'sister': 'assets/images/unit5/sister.png',
  'grandfather': 'assets/images/unit5/grandfather.png',
  'grandmother': 'assets/images/unit5/grandmother.png',
  'parents': 'assets/images/unit5/parents.png',
  'grandparents': 'assets/images/unit5/grandparents.png',
  'grandchild': 'assets/images/unit5/grandchild.png',
  'husband': 'assets/images/unit5/husband.png',
  'wife': 'assets/images/unit5/wife.png',
  'son': 'assets/images/unit5/son.png',
  'daughter': 'assets/images/unit5/daughter.png',
  'uncle': 'assets/images/unit5/uncle.png',
  'aunt': 'assets/images/unit5/aunt.png',
  'cousin': 'assets/images/unit5/cousin.png',
  'introduce': 'assets/images/unit5/introduce.png',
  'live': 'assets/images/unit5/live.png',
  'together': 'assets/images/unit5/together.png',
  // Unit 6
  'school': 'assets/images/unit6/school.png',
  'teacher': 'assets/images/unit6/teacher.png',
  'teach': 'assets/images/unit6/teach.png',
  'student': 'assets/images/unit6/student.png',
  'class': 'assets/images/unit6/class.png',
  'classroom': 'assets/images/unit6/classroom.png',
  'classmate': 'assets/images/unit6/classmate.png',
  'blackboard': 'assets/images/unit6/blackboard.png',
  'friend': 'assets/images/unit6/friend.png',
  'enter': 'assets/images/unit6/enter.png',
  'do': 'assets/images/unit6/do.png',
  'homework': 'assets/images/unit6/homework.png',
  'lesson': 'assets/images/unit6/lesson.png',
  'test': 'assets/images/unit6/test.png',
  'grade': 'assets/images/unit6/grade.png',
  'homeroom': 'assets/images/unit6/homeroom.png',
  'elementary': 'assets/images/unit6/elementary.png',
  'learn': 'assets/images/unit6/learn.png',
  'read': 'assets/images/unit6/read.png',
  'write': 'assets/images/unit6/write.png'
};

/* Emoji fallback for ALL words */
const WORD_EMOJI = {
  'knock':'🤛','door':'🚪','window':'🪟','clean':'🧹','dirty':'🗑️',
  'room':'🏠','living room':'🛋️','bedroom':'🛏️','bathroom':'🛁','kitchen':'🍳',
  'television':'📺','telephone':'📞','table':'🪑','newspaper':'📰','clock':'⏰',
  'curtain':'🪟','key':'🔑','vase':'🏺','umbrella':'☂️','roof':'🏠',
  'mirror':'🪞','soap':'🧼','toothbrush':'🪥','towel':'🧣','toilet':'🚽',
  'shower':'🚿','faucet':'🚰','shampoo':'🧴','bathtub':'🛁','toothpaste':'🪥',
  'comb':'💇','laundry':'🧺','washing machine':'🫧','iron':'👔','hanger':'🪝',
  'basket':'🧺','detergent':'🧪','dryer':'💨','fold':'👕','dry':'☀️',
  'desk':'🪑','lamp':'💡','bookshelf':'📚','drawer':'🗄️','pillow':'🛏️',
  'blanket':'🛌','alarm clock':'⏰','closet':'🚪','carpet':'🟫','poster':'🖼️',
  'computer':'💻','chair':'🪑','sofa':'🛋️','bed':'🛏️','fan':'🌀',
  'air conditioner':'❄️','heater':'🔥','refrigerator':'🧊','oven':'🫕','microwave':'📡',
  'shirt':'👕','pants':'👖','shoes':'👟','socks':'🧦','hat':'🧢',
  'coat':'🧥','dress':'👗','skirt':'👗','gloves':'🧤','scarf':'🧣',
  'boots':'🥾','sneakers':'👟','uniform':'👔','jacket':'🧥','sweater':'🧶',
  'tie':'👔','belt':'🪢','pocket':'👖','button':'🔘','zipper':'🤐',
  'father':'👨','mother':'👩','brother':'👦','sister':'👧','baby':'👶',
  'grandfather':'👴','grandmother':'👵','uncle':'👨','aunt':'👩','cousin':'🧒',
  'family':'👨‍👩‍👧‍👦','parents':'👫','son':'👦','daughter':'👧','husband':'🤵',
  'wife':'👰','children':'👧','twins':'👯','neighbor':'🏘️','friend':'🤝',
  'pet':'🐕','wedding':'💒',
  'school':'🏫','classroom':'🏫','teacher':'👩‍🏫','student':'🧑‍🎓','principal':'👨‍💼',
  'playground':'🎠','library':'📚','cafeteria':'🍽️','gym':'🏋️','hallway':'🚶',
  'locker':'🔒','blackboard':'📋','chalk':'✏️','eraser':'🧽','bell':'🔔',
  'homework':'📝','test':'📝','grade':'📊','report card':'📋','diploma':'📜',
  'pencil':'✏️','pen':'🖊️','notebook':'📓','textbook':'📕','ruler':'📏',
  'scissors':'✂️','glue':'🧴','crayon':'🖍️','marker':'🖊️','backpack':'🎒',
  'pencil case':'✏️','stapler':'📎','tape':'📎','paper':'📄','folder':'📁',
  'calculator':'🧮','dictionary':'📖','map':'🗺️','globe':'🌍','magnifying glass':'🔍',
  'study':'📖','exam':'📝','quiz':'❓','lesson':'📚','practice':'✍️',
  'learn':'📚','teach':'👩‍🏫','read':'📖','write':'✍️','answer':'✅',
  'question':'❓','mistake':'❌','correct':'✅','wrong':'❌','score':'💯',
  'pass':'✅','fail':'❌','cheat':'🚫','review':'📋','memorize':'🧠',
  'soccer':'⚽','baseball':'⚾','basketball':'🏀','tennis':'🎾','swimming':'🏊',
  'running':'🏃','jumping':'🤸','cycling':'🚴','skating':'⛸️','skiing':'⛷️',
  'volleyball':'🏐','badminton':'🏸','table tennis':'🏓','golf':'⛳','boxing':'🥊',
  'judo':'🥋','taekwondo':'🥋','yoga':'🧘','dance':'💃','gymnastics':'🤸',
  'game':'🎮','match':'🏆','team':'👥','player':'🏅','coach':'👨‍🏫',
  'winner':'🏆','loser':'😢','trophy':'🏆','medal':'🏅','champion':'🥇',
  'stadium':'🏟️','field':'🏟️','court':'🏸','pool':'🏊','track':'🏃',
  'race':'🏁','record':'📊','practice':'✍️','exercise':'🏋️','warm up':'🔥',
  'face':'😊','eye':'👁️','nose':'👃','mouth':'👄','ear':'👂',
  'hair':'💇','head':'🗣️','neck':'🦒','shoulder':'💪','chin':'😊',
  'forehead':'😊','cheek':'😊','lip':'👄','tongue':'👅','tooth':'🦷',
  'eyebrow':'🤨','eyelash':'👁️','freckle':'😊','dimple':'😊','wrinkle':'👴',
  'body':'🧍','arm':'💪','hand':'✋','finger':'☝️','leg':'🦵',
  'foot':'🦶','knee':'🦵','elbow':'💪','wrist':'⌚','ankle':'🦶',
  'toe':'🦶','thumb':'👍','nail':'💅','skin':'🤲','bone':'🦴',
  'red':'🔴','blue':'🔵','green':'🟢','yellow':'🟡','white':'⚪',
  'black':'⚫','orange':'🟠','purple':'🟣','pink':'💗','brown':'🟤',
  'heart':'❤️','muscle':'💪','stomach':'🤰','brain':'🧠','blood':'🩸',
  'health':'🏥','sick':'🤒','medicine':'💊','hospital':'🏥','doctor':'👨‍⚕️',
  'nurse':'👩‍⚕️','dentist':'🦷','fever':'🤒','cold':'🤧','cough':'😷',
  'headache':'🤕','pain':'😣','injection':'💉','bandage':'🩹','thermometer':'🌡️',
  'happy':'😊','sad':'😢','angry':'😠','scared':'😨','surprised':'😮',
  'tired':'😴','hungry':'🤤','thirsty':'💧','bored':'😑','excited':'🤩',
  'nervous':'😰','proud':'😎','shy':'🫣','jealous':'😒','lonely':'😔',
  'worried':'😟','confused':'😕','disappointed':'😞','grateful':'🙏','hopeful':'🤞',
  'love':'❤️','hate':'😡','laugh':'😂','cry':'😭','smile':'😊',
  'frown':'☹️','hug':'🤗','kiss':'😘','wave':'👋','shake hands':'🤝',
  'morning':'🌅','afternoon':'☀️','evening':'🌆','night':'🌙','noon':'☀️',
  'midnight':'🌑','sunrise':'🌅','sunset':'🌇','dawn':'🌤️','dusk':'🌆',
  'today':'📅','yesterday':'⏪','tomorrow':'⏩','week':'📆','month':'🗓️',
  'year':'📅','hour':'🕐','minute':'⏱️','second':'⏱️','time':'⏰',
  'Monday':'📅','Tuesday':'📅','Wednesday':'📅','Thursday':'📅','Friday':'📅',
  'Saturday':'📅','Sunday':'📅',
  'spring':'🌸','summer':'☀️','fall':'🍂','autumn':'🍁','winter':'❄️',
  'January':'📅','February':'💝','March':'🌿','April':'🌷','May':'🌺',
  'June':'☀️','July':'🎆','August':'🏖️','September':'🍎','October':'🎃',
  'November':'🍂','December':'🎄',
  'birthday':'🎂','cake':'🎂','candle':'🕯️','gift':'🎁','party':'🎉',
  'balloon':'🎈','card':'💌','wish':'⭐','celebrate':'🥳','invitation':'💌',
  'number':'🔢','one':'1️⃣','two':'2️⃣','three':'3️⃣','four':'4️⃣',
  'five':'5️⃣','six':'6️⃣','seven':'7️⃣','eight':'8️⃣','nine':'9️⃣',
  'ten':'🔟','hundred':'💯','thousand':'🔢','million':'🔢','zero':'0️⃣',
  'store':'🏪','shop':'🛍️','bank':'🏦','post office':'🏤','police station':'🚔',
  'fire station':'🚒','hospital':'🏥','church':'⛪','restaurant':'🍽️','hotel':'🏨',
  'supermarket':'🛒','bakery':'🍞','pharmacy':'💊','gas station':'⛽','airport':'✈️',
  'station':'🚉','park':'🌳','museum':'🏛️','theater':'🎭','zoo':'🐘',
  'north':'⬆️','south':'⬇️','east':'➡️','west':'⬅️','left':'👈',
  'right':'👉','up':'⬆️','down':'⬇️','front':'🔜','back':'🔙',
  'near':'📍','far':'🌄','here':'📌','there':'👉','between':'↔️',
  'next to':'↔️','behind':'🔙','inside':'📥','outside':'📤','across':'↔️',
  'market':'🏪','price':'💰','money':'💵','coin':'🪙','bill':'💵',
  'buy':'🛒','sell':'💰','pay':'💳','change':'🪙','receipt':'🧾',
  'cheap':'💲','expensive':'💎','discount':'🏷️','sale':'🏷️','shopping':'🛍️',
  'wallet':'👛','purse':'👜','credit card':'💳','cash':'💵','check':'📋',
  'save':'🐷','spend':'💸','borrow':'🤝','lend':'🤲','rich':'💰',
  'poor':'😔','account':'🏦','deposit':'💰','withdraw':'💸','interest':'📈',
  'cook':'👨‍🍳','bake':'🍞','boil':'♨️','fry':'🍳','grill':'🔥',
  'mix':'🥣','stir':'🥄','chop':'🔪','peel':'🥕','pour':'🫗',
  'taste':'👅','smell':'👃','recipe':'📝','ingredient':'🧅','spice':'🌶️',
  'salt':'🧂','sugar':'🍬','pepper':'🌶️','oil':'🫒','butter':'🧈',
  'bread':'🍞','rice':'🍚','noodle':'🍜','soup':'🍲','salad':'🥗',
  'meat':'🥩','fish':'🐟','chicken':'🍗','egg':'🥚','cheese':'🧀',
  'hobby':'🎯','music':'🎵','singing':'🎤','painting':'🎨','drawing':'✏️',
  'reading':'📖','writing':'✍️','cooking':'👨‍🍳','gardening':'🌱','fishing':'🎣',
  'camping':'⛺','hiking':'🥾','photography':'📷','knitting':'🧶','chess':'♟️',
  'piano':'🎹','guitar':'🎸','drum':'🥁','violin':'🎻','flute':'🎵',
  'concert':'🎼','singer':'🎤','band':'🎸','song':'🎵','dance':'💃',
  'country':'🌍','city':'🏙️','village':'🏘️','town':'🏘️','capital':'🏛️',
  'travel':'✈️','trip':'🧳','vacation':'🏖️','tour':'🗺️','passport':'📕',
  'ticket':'🎫','luggage':'🧳','suitcase':'🧳','map':'🗺️','guide':'📗',
  'car':'🚗','bus':'🚌','train':'🚆','airplane':'✈️','ship':'🚢',
  'bicycle':'🚲','motorcycle':'🏍️','taxi':'🚕','subway':'🚇','boat':'⛵',
  'truck':'🚛','ambulance':'🚑','helicopter':'🚁','rocket':'🚀','van':'🚐',
  'tent':'⛺','campfire':'🔥','forest':'🌲','mountain':'⛰️','river':'🏞️',
  'lake':'🏞️','beach':'🏖️','island':'🏝️','desert':'🏜️','waterfall':'💦',
  'tree':'🌳','flower':'🌸','grass':'🌿','leaf':'🍃','seed':'🌱',
  'movie':'🎬','film':'🎞️','actor':'🎭','actress':'🎭','director':'🎬',
  'screen':'📺','popcorn':'🍿','ticket':'🎫','scene':'🎬','camera':'📷',
  'festival':'🎉','parade':'🎊','fireworks':'🎆','costume':'🎃','mask':'🎭',
  'roller coaster':'🎢','ferris wheel':'🎡','carousel':'🎠','bumper car':'🚗','water slide':'💦',
  'letter':'✉️','stamp':'📮','envelope':'✉️','address':'🏠','package':'📦',
  'mail':'📬','postcard':'📮','send':'📤','receive':'📥','deliver':'📦',
  'wheat':'🌾','corn':'🌽','flour':'🫘','cereal':'🥣','oatmeal':'🥣',
  'apple':'🍎','banana':'🍌','grape':'🍇','strawberry':'🍓','watermelon':'🍉',
  'peach':'🍑','pear':'🍐','cherry':'🍒','lemon':'🍋','pineapple':'🍍',
  'tomato':'🍅','carrot':'🥕','potato':'🥔','onion':'🧅','cucumber':'🥒',
  'pepper':'🫑','broccoli':'🥦','mushroom':'🍄','pumpkin':'🎃','corn':'🌽',
  'farm':'🌾','farmer':'👨‍🌾','cow':'🐄','pig':'🐷','horse':'🐴',
  'sheep':'🐑','chicken':'🐔','duck':'🦆','goat':'🐐','rabbit':'🐰',
  'ant':'🐜','bee':'🐝','butterfly':'🦋','spider':'🕷️','ladybug':'🐞',
  'caterpillar':'🐛','grasshopper':'🦗','mosquito':'🦟','fly':'🪰','snail':'🐌',
  'lion':'🦁','tiger':'🐅','elephant':'🐘','giraffe':'🦒','bear':'🐻',
  'monkey':'🐒','zebra':'🦓','hippo':'🦛','rhino':'🦏','deer':'🦌',
  'wolf':'🐺','fox':'🦊','snake':'🐍','crocodile':'🐊','penguin':'🐧',
  'eagle':'🦅','parrot':'🦜','owl':'🦉','dolphin':'🐬','whale':'🐋',
  'earth':'🌍','nature':'🌿','environment':'🌎','pollution':'🏭','recycle':'♻️',
  'ocean':'🌊','sea':'🌊','wave':'🌊','sand':'🏖️','coral':'🪸',
  'shark':'🦈','octopus':'🐙','turtle':'🐢','crab':'🦀','jellyfish':'🪼',
  'starfish':'⭐','seashell':'🐚','seaweed':'🌿','submarine':'🚢','lighthouse':'🗼',
  'sky':'🌤️','cloud':'☁️','star':'⭐','moon':'🌙','sun':'☀️',
  'rainbow':'🌈','thunder':'⚡','lightning':'⚡','wind':'💨','storm':'🌩️',
  'rain':'🌧️','snow':'❄️','fog':'🌫️','ice':'🧊','hail':'🌨️',
  'sunny':'☀️','cloudy':'☁️','rainy':'🌧️','snowy':'❄️','windy':'💨',
  'hot':'🥵','cold':'🥶','warm':'🌡️','cool':'😎','humid':'💧',
  'temperature':'🌡️','degree':'🌡️','forecast':'📊','season':'🍃','weather':'🌤️',
  'energy':'⚡','solar':'☀️','power':'💪','electricity':'⚡','battery':'🔋',
  'eye':'👁️','see':'👀','hear':'👂','touch':'✋','feel':'💭',
  'circle':'⭕','square':'⬜','triangle':'🔺','rectangle':'▬','diamond':'💎',
  'star':'⭐','oval':'🥚','cube':'🧊','sphere':'🌐','cylinder':'🥫',
  'walk':'🚶','run':'🏃','jump':'🤸','swim':'🏊','climb':'🧗',
  'fly':'✈️','drive':'🚗','ride':'🚴','push':'👐','pull':'🤏',
  'kick':'🦶','throw':'🤾','catch':'🤲','hit':'👊','carry':'💪',
  'job':'💼','work':'💼','office':'🏢','boss':'👨‍💼','employee':'👷',
  'doctor':'👨‍⚕️','police officer':'👮','firefighter':'👨‍🚒','pilot':'👨‍✈️','chef':'👨‍🍳',
  'artist':'🎨','scientist':'🔬','engineer':'👷','lawyer':'⚖️','journalist':'📰',
  'astronaut':'👨‍🚀','soldier':'💂','detective':'🕵️','mechanic':'🔧','electrician':'⚡',
  'problem':'❓','solve':'✅','idea':'💡','think':'🤔','decide':'🎯',
  'plan':'📋','create':'🎨','build':'🏗️','fix':'🔧','break':'💔',
  'world':'🌍','culture':'🎭','language':'🗣️','tradition':'🏛️','history':'📜',
  'future':'🔮','technology':'💻','robot':'🤖','internet':'🌐','space':'🚀',
  'planet':'🪐','satellite':'🛸','universe':'🌌','galaxy':'🌌','telescope':'🔭',
  'invent':'💡','discover':'🔍','explore':'🧭','experiment':'🔬','research':'📊',
  'dream':'💭','hope':'🤞','wish':'⭐','believe':'💫','imagine':'💭'
};

function getWordImage(english) {
  const key = english.toLowerCase();
  return WORD_IMAGES[key] || null;
}

function getWordEmoji(english) {
  const key = english.toLowerCase();
  return WORD_EMOJI[key] || '📝';
}
